### ISSUE TITLE
CyaSSL recipe is missing

### ISSUE THREAD

**Issue by mechalas** [wolfSSL/meta-wolfssl#1]
The recipe for cyassl was deleted from the master branch on the July 30 2014 commit.

**Comment by lchristina26** [comment]
Hi mechalas, the cyassl recipe is now located in the openembedded meta-networking [repository](https://github.com/openembedded/meta-oe/tree/master/meta-networking/recipes-connectivity/cyassl). I apologize for the confusion and I will update the README to reflect these changes.
