### ISSUE TITLE
Github Security Update Breaks Build

### ISSUE THREAD

**Issue by sharkness-aurora** [wolfSSL/meta-wolfssl#28]
I'll preface this by saying I'm a yocto novice at best.

I tried adding wolfssl to my layers, cloning the `meta-wolfssl` repo to my poky directory, and adding `wolfssl wolfcrypttest wolfcryptbenchmark` to my `IMAGE_INSTALL`, but I ran into the new Github Security change.

```
ERROR: wolfssl-5.2.0-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; unset _PYTHON_SYSCONFIGDATA_NAME; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1001/bus"; export SSH_AGENT_PID="2856"; export SSH_AUTH_SOCK="/run/user/1001/keyring/ssh";
...
git -c core.fsyncobjectfiles=0 ls-remote git://github.com/wolfssl/wolfssl.git  failed with exit code 128, output:
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

After touching each of the recipes to change `git://` to `https://`, and adding a md5 checksum to the `SRC_URI`, I'm now running into an issue where the `do_compile` step of the wolfssl recipe is failing.

```
./autogen.sh: not found
```

**Comment by dgarske** [comment]
Can you try using the public https GitHub remote instead using `https://github.com/wolfSSL/wolfssl.git`?

**Comment by sharkness-aurora** [comment]
Here's the change I made to make `do_fetch` not complain.

```
SRC_URI = "https://github.com/wolfssl/wolfssl.git;nobranch=1;tag=v${PV}-stable;"
SRC_URI[md5sum] = "28546cd358b98c6b22d76710e2f6cd82"
```

**Comment by dgarske** [comment]
Hi @sharkness-aurora , to confirm using the public https SRC_URI resolved the issue? Let us know if you have any other questions. Thanks, David Garske, wolfSSL

**Comment by sharkness-aurora** [comment]
The switch to the public https SRC_URI resolved the issue present in `do_fetch`, but now I'm running into the issue I stated above in `do_compile`, where the git repo is not being downloaded, unpacked, or something else I'm not understanding. I'm very novice when it comes to yocto/bitbake recipes, so I'm not sure what the issue is exactly.

After the `do_fetch` recipe runs, I can look into the build folder and see this structure.

```
tree build/tmp/work/aarch64-poky-linux/wolfssl/5.2.0-r0/ -L 2
build/tmp/work/aarch64-poky-linux/wolfssl/5.2.0-r0/
├── build
├── git
├── recipe-sysroot
│   ├── lib
│   ├── sysroot-providers
│   └── usr
├── recipe-sysroot-native
│   ├── etc
│   ├── installeddeps
│   ├── sysroot-providers
│   └── usr
├── temp
│   ├── log.do_configure -> log.do_configure.8380
│   ├── log.do_configure.8380
│   ├── log.do_fetch -> log.do_fetch.7951
│   ├── log.do_fetch.7951
│   ├── log.do_patch -> log.do_patch.7967
│   ├── log.do_patch.7967
│   ├── log.do_prepare_recipe_sysroot -> log.do_prepare_recipe_sysroot.7956
│   ├── log.do_prepare_recipe_sysroot.7956
│   ├── log.do_unpack -> log.do_unpack.7954
│   ├── log.do_unpack.7954
│   ├── log.task_order
│   ├── run.autotools_aclocals.8380
│   ├── run.autotools_preconfigure.8380
│   ├── run.base_do_fetch.7951
│   ├── run.base_do_unpack.7954
│   ├── run.clean_recipe_sysroot.7951
│   ├── run.do_configure -> run.do_configure.8380
│   ├── run.do_configure.8380
│   ├── run.do_fetch -> run.do_fetch.7951
│   ├── run.do_fetch.7951
│   ├── run.do_patch -> run.do_patch.7967
│   ├── run.do_patch.7967
│   ├── run.do_prepare_recipe_sysroot -> run.do_prepare_recipe_sysroot.7956
│   ├── run.do_prepare_recipe_sysroot.7956
│   ├── run.do_qa_patch.7967
│   ├── run.do_qa_unpack.7954
│   ├── run.do_unpack -> run.do_unpack.7954
│   ├── run.do_unpack.7954
│   ├── run.extend_recipe_sysroot.7951
│   ├── run.extend_recipe_sysroot.7956
│   ├── run.extend_recipe_sysroot.7967
│   └── run.patch_do_patch.7967
└── wolfssl.git
```

**Comment by sharkness-aurora** [comment]
I see in the recipe that `S = "${WORKDIR}/git"`, but the git folder doesn't seem to have anything in it.

**Comment by dgarske** [comment]
Hi @sharkness-aurora ,

I am not sure what would cause that. The yocto bike bake usually synchronizes that. Can you share the steps you are using so we can attempt to reproduce?

Thanks,
David Garske, wolfSSL

**Comment by JacobBarthelmeh** [comment]
Hi @sharkness-aurora and @dgarske ,

I was able to reproduce the issue and am testing out a fix. Will link this issue in the upcoming PR if the fix passes.

Regards,
Jacob

**Comment by JacobBarthelmeh** [comment]
Hi @sharkness-aurora ,

Can you confirm that having the protocol set to https also resolves the issue locally for you?
https://github.com/wolfSSL/meta-wolfssl/pull/29

Regards,
Jacob
