### ISSUE TITLE
error in curl_7.37.1.bbappend

### ISSUE THREAD

**Issue by bharti2810** [wolfSSL/meta-wolfssl#3]
Parsing recipes: 100% |#########################################################################################################| Time: 00:00:40
Parsing of 2269 .bb files complete (0 cached, 2269 parsed). 2835 targets, 152 skipped, 5 masked, 0 errors.
ERROR: No recipes available for:
  /home/kpit/VAB-820_Linux_BSP_v4.1.3_20180208/Sourcecode/via-release-bsp/sources/meta-wolfssl/recipes-support/curl/curl_7.37.1.bbappend

Summary: There was 1 WARNING message shown.

**Comment by cconlon** [comment]
This issue has been answered via wolfSSL internal support.  Copying the answer here for public reference, and closing this issue.

The curl_7.37.1.bbappend expects curl 7.37.1 to be available in your image build.  If it cannot be found, the above error will be shown.  The current "meta-wolfssl" layer fixes this issue by changing the curl bbappend to a generic version ("curl_%.bbappend"), which should work if you have any current version of cURL available.

If you do not have cURL available in your image, you can delete this .bbappend file before compiling the meta-wolfssl layer.
