### ISSUE TITLE
Update wolfSSL version on Kirkstone Branch

### ISSUE THREAD

**Issue by avlec** [wolfSSL/meta-wolfssl#47]
The version is a few out of date. I've tried tweaking the recipe for 5.5.4 and that modification is trivial and seems to work. Upgrading to 5.6.0 is a different story the options.h.in seems to generate options.h in a different directory and the configure script seems to get hung up after that.

| configure: Generating user options header...
| checking for wolfssl/openssl/aes.h... no
| configure: error: Error including wolfssl/openssl/aes.h. Possible circular dependency introduced or missing include.

**Comment by JacobBarthelmeh** [comment]
This PR built with the newer wolfssl 5.6.0 (https://github.com/wolfSSL/meta-wolfssl/pull/48). It pulls in the patch for corlm vs cut use when creating options.h. If it still fails with those changes please provide steps to reproduce starting with a clean slate.

**Comment by avlec** [comment]
@JacobBarthelmeh I will try to spin of a build in the next day or two here and will let you know how it goes.

**Comment by avlec** [comment]
Completed in #48
