### ISSUE TITLE
WolfProvider adds -DWOLFSSL_PSS_LONG_SALT -DWOLFSSL_PSS_SALT_LEN_DISCOVER when building for FIPS

### ISSUE THREAD

**Issue by G-E-N-E** [wolfSSL/meta-wolfssl#89]
According to the WolfProvider README, https://github.com/wolfSSL/wolfProvider, -DWOLFSSL_PSS_LONG_SALT -DWOLFSSL_PSS_SALT_LEN_DISCOVER options should be dropped when building from FIPS or FIPS-ready bundles. As the recipe doesn't have a condition on the WOLFSSL_TYPE it's always added and the WolfSSL fips/fips-ready recipes do not remove the added options (Trying to remove them would probably be worse than simply not adding them since it would be dependent on the ordering of the bbappends being parsed which from my experience is hard to predict).

Suggested Fix: Drop "-DWOLFSSL_PSS_LONG_SALT -DWOLFSSL_PSS_SALT_LEN_DISCOVER" from the existing CPPFLAGS += and Add a CPPFLAGS += "-DWOLFSSL_PSS_LONG_SALT -DWOLFSSL_PSS_SALT_LEN_DISCOVER" conditioned on the WOLFSSL_TYPE.

CPPFLAGS += " -DHAVE_AES_ECB -DWOLFSSL_AES_DIRECT -DWC_RSA_NO_PADDING -DWOLFSSL_PUBLIC_MP -DECC_MIN_KEY_SZ=192 -DHAVE_PUBLIC_FFDHE -DWOLFSSL_DH_EXTRA ${@'-DWOLFSSL_PSS_LONG_SALT -DWOLFSSL_PSS_SALT_LEN_DISCOVER' if d.getVar('WOLFSSL_TYPE')  not in ("fips", "fips-ready") else ''}"

**Comment by embhorn** [comment]
Hi @G-E-N-E 

Thanks for creating this issue. I've added the change you suggested. Please let me know if that addresses your concern.

Cheers,
@embhorn - wolfSSL Support
